// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as plugins$0 from "../../../../../ltools/internal/plugins/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "calculator:error": string;
            "calculator:history": string;
            "calculator:result": string;
            "clipboard:cleared": string;
            "clipboard:count": string;
            "clipboard:deleted": string;
            "clipboard:heartbeat": string;
            "clipboard:new": string;
            "clipboard:permission:requested": string;
            "datetime:current": string;
            "datetime:date": string;
            "datetime:datetime": string;
            "datetime:day": number;
            "datetime:hour": number;
            "datetime:minute": number;
            "datetime:month": number;
            "datetime:second": number;
            "datetime:time": string;
            "datetime:weekday": string;
            "datetime:year": number;
            "hosts:backup:created": string;
            "hosts:backup:deleted": string;
            "hosts:backup:restored": string;
            "hosts:entry:added": string;
            "hosts:entry:removed": string;
            "hosts:entry:updated": string;
            "hosts:error": string;
            "hosts:scenario:created": string;
            "hosts:scenario:deleted": string;
            "hosts:scenario:switched": string;
            "hosts:scenario:updated": string;
            "jsoneditor:error": string;
            "jsoneditor:formatted": string;
            "jsoneditor:validated": boolean;
            "kanban:board:created": string;
            "kanban:board:deleted": string;
            "kanban:board:updated": string;
            "kanban:card:completed": string;
            "kanban:card:created": string;
            "kanban:card:deleted": string;
            "kanban:card:moved": string;
            "kanban:card:uncompleted": string;
            "kanban:card:updated": string;
            "kanban:checklist:added": string;
            "kanban:checklist:removed": string;
            "kanban:checklist:toggled": string;
            "kanban:checklist:updated": string;
            "kanban:column:created": string;
            "kanban:column:deleted": string;
            "kanban:column:moved": string;
            "kanban:column:updated": string;
            "kanban:label:created": string;
            "kanban:label:deleted": string;
            "kanban:label:updated": string;
            "notification:show": string;
            "processmanager:error": string;
            "processmanager:killed": string;
            "processmanager:updated": string;
            "qrcode:copied": string;
            "qrcode:generated": string;
            "qrcode:saved": string;
            "screenshot2:cancelled": string;
            "screenshot2:captured": string;
            "screenshot2:copied": string;
            "screenshot2:displays-info": string;
            "screenshot2:error": string;
            "screenshot2:image-data": string;
            "screenshot2:saved": string;
            "screenshot2:session-end": string;
            "screenshot2:session-start": string;
            "screenshot2:started": string;
            "search:closed": string;
            "search:opened": string;
            "search:results": (plugins$0.SearchResult | null)[];
            "shortcut:permission-required": string;
            "shortcut:triggered": string;
            "sysinfo:cpu": string;
            "sysinfo:gc": string;
            "sysinfo:maxprocs": string;
            "sysinfo:updated": string;
            "sysinfo:uptime": string;
            "tunnel:created": string;
            "tunnel:deleted": string;
            "tunnel:error": any;
            "tunnel:install:progress": string;
            "tunnel:log": any;
            "tunnel:options:updated": string;
            "tunnel:restarting": string;
            "tunnel:started": string;
            "tunnel:stopped": string;
            "tunnel:updated": string;
            "tunnel:url": any;
        }
    }
}
