//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugins$0 from "../../../../../ltools/internal/plugins/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "search:results": $$createType2,
    }));
}

// Private type creation functions
const $$createType0 = plugins$0.SearchResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);

configure();
