// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as plugins$0 from "../../../../../ltools/internal/plugins/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "calculator:error": string;
            "calculator:history": string;
            "calculator:result": string;
            "clipboard:cleared": string;
            "clipboard:count": string;
            "clipboard:deleted": string;
            "clipboard:heartbeat": string;
            "clipboard:new": string;
            "clipboard:permission:requested": string;
            "datetime:current": string;
            "datetime:date": string;
            "datetime:datetime": string;
            "datetime:day": number;
            "datetime:hour": number;
            "datetime:minute": number;
            "datetime:month": number;
            "datetime:second": number;
            "datetime:time": string;
            "datetime:weekday": string;
            "datetime:year": number;
            "jsoneditor:error": string;
            "jsoneditor:formatted": string;
            "jsoneditor:validated": boolean;
            "processmanager:error": string;
            "processmanager:killed": string;
            "processmanager:updated": string;
            "screenshot:cancelled": string;
            "screenshot:captured": string;
            "screenshot:copied": string;
            "screenshot:error": string;
            "screenshot:saved": string;
            "screenshot:started": string;
            "search:closed": string;
            "search:opened": string;
            "search:results": (plugins$0.SearchResult | null)[];
            "shortcut:permission-required": string;
            "shortcut:triggered": string;
            "sysinfo:cpu": string;
            "sysinfo:gc": string;
            "sysinfo:maxprocs": string;
            "sysinfo:updated": string;
            "sysinfo:uptime": string;
        }
    }
}
