package sync

import (
	"path/filepath"
	"strings"
)

// IgnoreRules manages file exclusion patterns for synchronization.
type IgnoreRules struct {
	patterns []string
}

// DefaultIgnorePatterns contains patterns that are always excluded from sync.
var DefaultIgnorePatterns = []string{
	// Large model files
	"localtranslate/models/",
	"*.gguf",
	"*.bin",

	// Update files
	"updates",

	// Music Server files
	"lx-music-service",

	// Temporary files
	"*.tmp",
	"*.log",
	"*.partial",
	".DS_Store",
	"Thumbs.db",

	// Sync configuration itself (avoid recursive sync)
	"sync.json",

	// Git directory
	".sync/",
}

// NewIgnoreRules creates a new IgnoreRules with default patterns.
func NewIgnoreRules() *IgnoreRules {
	return &IgnoreRules{
		patterns: append([]string{}, DefaultIgnorePatterns...),
	}
}

// AddPattern adds a custom ignore pattern.
func (r *IgnoreRules) AddPattern(pattern string) {
	r.patterns = append(r.patterns, pattern)
}

// AddPatterns adds multiple custom ignore patterns.
func (r *IgnoreRules) AddPatterns(patterns []string) {
	r.patterns = append(r.patterns, patterns...)
}

// ShouldIgnore checks if a file path should be ignored.
// The path should be relative to the data directory.
func (r *IgnoreRules) ShouldIgnore(relPath string) bool {
	// Normalize path separators
	relPath = filepath.ToSlash(relPath)

	for _, pattern := range r.patterns {
		if r.matchPattern(relPath, pattern) {
			return true
		}
	}
	return false
}

// matchPattern checks if a path matches a single ignore pattern.
func (r *IgnoreRules) matchPattern(path, pattern string) bool {
	// Normalize pattern
	pattern = filepath.ToSlash(pattern)

	// Handle directory patterns (ending with /)
	if strings.HasSuffix(pattern, "/") {
		// Check if path is inside the directory
		dirPattern := strings.TrimSuffix(pattern, "/")
		if path == dirPattern || strings.HasPrefix(path, dirPattern+"/") {
			return true
		}
		return false
	}

	// Handle wildcard patterns
	if strings.Contains(pattern, "*") {
		matched, err := filepath.Match(pattern, filepath.Base(path))
		if err == nil && matched {
			return true
		}
		// Also try matching the full path
		matched, err = filepath.Match(pattern, path)
		if err == nil && matched {
			return true
		}
		return false
	}

	// Exact match
	if path == pattern {
		return true
	}

	// Check if path is inside a directory that matches
	if strings.HasPrefix(path, pattern+"/") {
		return true
	}

	return false
}

// ToGitignore converts the ignore rules to .gitignore format.
func (r *IgnoreRules) ToGitignore() string {
	var sb strings.Builder
	sb.WriteString("# Auto-generated by LTools sync\n")
	for _, pattern := range r.patterns {
		sb.WriteString(pattern)
		sb.WriteString("\n")
	}
	return sb.String()
}

// GetPatterns returns all ignore patterns.
func (r *IgnoreRules) GetPatterns() []string {
	return append([]string{}, r.patterns...)
}
